config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :electricity_infos, only: [:index, :create, :new]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/electricity_info.rb
class ElectricityInfo < ApplicationRecord
  validates_presence_of :pdl_id
  validates_presence_of :begin_at
  validates_presence_of :end_at
  validates_presence_of :index_start
  validates_presence_of :index_end
  validates_presence_of :consumption

  def self.upload_xml_file file_data
    result = {success: "", errors: ""}
    result[:errors] << "Must be a XML file." and return result unless file_data.respond_to?(:read) and file_data.content_type == 'text/xml'

    electricity_info = {}
    xml_contents = file_data.read
    hash = Hash.from_xml(xml_contents.gsub("\n", ""))
    clients = hash["Index_C5"]["Corps_de_fichier_par_PDL"] rescue nil

    if clients.nil?
      result[:errors] << "Your file doesn't contain any clients well formated."
    else
      clients.each_with_index do |client, index|
        electricity_info[:pdl_id] = client["Identifiant_Stable_PDL"].to_i
        electricity_info[:begin_at] = client["Situation_Contrat"]["Date_Debut_Consommation"] rescue nil
        electricity_info[:end_at] = client["Situation_Contrat"]["Date_Fin_Consommation"] rescue nil
        electricity_info[:index_start] = client["Situation_Contrat"]["Compteur"]["Periode"]["Donnees_Cadran"]["Index_Debut_Consommation"] rescue nil
        electricity_info[:index_end] = (client["Situation_Contrat"]["Compteur"]["Periode"]["Donnees_Cadran"]["Index_A_Facturer"] rescue nil) || '0'
        electricity_info[:consumption] = client["Situation_Contrat"]["Compteur"]["Periode"]["Donnees_Cadran"]["Consommation_Cadran"] rescue nil

        result[:errors] << "The #{index}th client is missing some required informations." and next if electricity_info.values.include? nil
        ei = ElectricityInfo.create(electricity_info)
        result[:success] = "All client(s) without error(s) have been uploaded succesfully." if ei.id
      end
    end

    result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/electricity_infos_controller.rb
class ElectricityInfosController < ApplicationController
  def index
    @electricity_infos = ElectricityInfo.order(:created_at).paginate(page: params[:page], per_page: 10)
  end

  def create
    file_data = params[:uploaded_file].try(:[], :xml)
    result = ElectricityInfo.upload_xml_file(file_data)
    flash[:success] = result[:success] if result[:success].present?
    flash[:danger] = result[:errors] if result[:errors].present?
    redirect_to new_electricity_info_path and return
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/electricity_info_helper.rb
module ElectricityInfoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/electricity_infos/index.html.slim
- attrs = controller_name.classify.constantize.column_names - ['id', 'updated_at', 'created_at']
.infos-table
  h1 All meter readings of electricity
  table.table
    thead
      tr
        - attrs.each do |column|
          th
            = column.humanize
    tbody
      - @electricity_infos.each do |item|
        tr
          - attrs.each do |attr|
            td
              .center
                = item.send(attr)
  = will_paginate @electricity_infos

app/views/electricity_infos/new.html.slim
main.inner.cover role="main" 
  h1.cover-heading Upload new electricity infos
  p.lead Your file must be a XML type and contain all needed informations.

  = simple_form_for :uploaded_file, url: electricity_infos_path, :html=> {:multipart=>true} do |f|
    .masthead
      = f.file_field :xml, class: 'btn btn-secondary'
    p.lead
      = f.submit 'upload', class: 'btn btn-lg btn-secondary'

app/views/home/index.html.slim
main.inner.cover role="main" 
  h1.cover-heading Little Sandbox Application
  p.lead A simple Ruby on Rails app for training.

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    title Sandbox
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'favicon.png', :rel => 'shortcut icon'
    - if flash.any?
      .flashes
        - flash.each do |key, value|
          .alert class: "alert-#{key}" 
            = value
  body
    .cover-container.d-flex.h-100.p-3.mx-auto.flex-column
      header.masthead.mb-auto
        .inner
          h3.masthead-brand Heroes Chronicle
          nav.nav.nav-masthead.justify-content-center
            = link_to 'Home', root_path, class: "nav-link #{'active'if current_page?(root_path)}"
            = link_to 'Upload new infos', new_electricity_info_path, class: "nav-link #{'active'if current_page?(new_electricity_info_path)}"
            = link_to 'See all infos', electricity_infos_path, class: "nav-link #{'active'if current_page?(electricity_infos_path)}"
      = yield
      footer.mt-auto